export const mumbleFlavours: ((userName: string) => void)[] = [
(name) => `${name} mumbles mindlessly.`,
(name) => `${name} tries to speak, but fails to form any coherent sentences.`,
(name) => `${name} lets out a blissful moan.`,
(name) => `${name} makes some sounds with their mouth.`,
(name) => `${name} looks into the distance with unfocused eyes, flapping their mouth slowly.`,
(name) => `${name} watches the conversation with eyes glazed over.`,
(name) => `${name}'s head flops mindlessly to the side.`,
(name) => `${name} tries to speak, but the drool pouring out makes it impossible, not to mention their mindlessness.`,
(name) => `Whatever ${name} is doing, it isn't speaking.`,
(name) => `${name}'s mind wanders off into the distance.`,
(name) => `${name} turns their finger round and round, slowly in front of their face.`,
(name) => `${name} tries to speak, but a stream of drool comes out instead`,
(name) => `${name} spouts a slew of lewd rambling`,
(name) => `${name} lets out a needy moan`,
(name) => `${name} runs their hands on their skin.`,
(name) => `${name} tries to speak, but can only think about pleasing his caretaker`,
];
