export const CREATE_COMMAND = "!s create";
export const JOIN_COMMAND = "!s join";
export const CANCEL_CREATE_COMMAND = "!s cancelCreate";
export const START_COMMAND = "!s start";
export const ROLE_COMMAND = "!s role";
export const VOTE_COMMAND = "!s vote {player name}";
export const ENTHRALL_COMMAND = "!s convert {player name}";
export const NO_FORCE_COMMAND = "!s no_force";
export const FORCE_COMMAND = "!s force {person to vote for}";